# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_auto_20170529_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario',
        ),
    ]
